### ISSUE TITLE
Bug with upui normalisation

### ISSUE THREAD

**Issue by chrisquince** [xapple/seqenv#3]
Running sequences through the upui normalisation gives error:

    seqenv AllSites_C05.fa --min_identity 0.95 --num_threads 32 --out_dir All_95_upui --min_coverage 0.95 --max_targets 100 --normalization upui            
    seqenv version 1.1.4 (pid 60382)
    The exact version of the code is: 4e407e1
    Start at: 2016-05-03 13:34:45.570319
    --> STEP 1: Parse the input FASTA file.
    Elapsed time: 0:00:00.046785
    Using: All_95_upui/renamed.fasta
    --> STEP 2: Similarity search against the 'nt' database with 32 processes
    Elapsed time: 0:01:33.193498
    --> STEP 3: Filter out bad hits from the search results
    Elapsed time: 0:00:00.017426
    --> STEP 4: Parsing the search results
    Elapsed time: 0:00:00.027052
    --> STEP 5: Setting up the SQLite3 database connection.
    Elapsed time: 0:00:00.000913
    Got 4114 GI hits and 3851 of them had one or more EnvO terms associated.
    --> STEP 6: Computing EnvO term frequencies.
    Traceback (most recent call last):
      File "/home/chris/repos/seqenv/seqenv/seqenv", line 68, in <module>
        seqenv.Analysis(input_path, **kwargs).run()
      File "/home/chris/repos/seqenv/seqenv/analysis.py", line 151, in run
        self.outputs.make_all()
      File "/home/chris/repos/seqenv/seqenv/outputs.py", line 40, in make_all
        self.tsv_seq_to_concepts()
      File "/home/chris/repos/seqenv/seqenv/outputs.py", line 93, in tsv_seq_to_concepts
        content = self.df_seqs_concepts.to_csv(None, sep=self.sep, float_format=self.float_format)
      File "/home/chris/repos/seqenv/seqenv/common/cache.py", line 35, in retrieve_from_cache
        else: result = f(self)
      File "/home/chris/repos/seqenv/seqenv/outputs.py", line 53, in df_seqs_concepts
        df = pandas.DataFrame(self.a.seq_to_counts)
      File "/home/chris/repos/seqenv/seqenv/common/cache.py", line 35, in retrieve_from_cache
        else: result = f(self)
      File "/home/chris/repos/seqenv/seqenv/analysis.py", line 396, in seq_to_counts
        if not results: raise Exception("We found no isolation sources with your input. Sorry.")
    Exception: We found no isolation sources with your input. Sorry.

**Comment by xapple** [comment]
The error message you got is the following: `Exception: We found no isolation sources with your input. Sorry. ` and there is nothing we can do about that.

Do you think it should have found isolation sources ? And if so why and which ones ?

**Comment by chrisquince** [comment]
Well I ran the same sequences through all four normalisations all but upui found isolation sources and generated output. Therefore I concluded this was an error.

**Comment by xapple** [comment]
OK that's more interesting then. Could you try with the test dataset first instead of a custom dataset ?

**Comment by xapple** [comment]
Fixed in version 1.1.5
