### ISSUE TITLE
REAME.md file placement during install

### ISSUE THREAD

**Issue by jmtsuji** [xapple/seqenv#5]
Running 'pip install seqenv' places the seqenv program in /usr/local/bin. However, an error message occurs in the first run:

Traceback (most recent call last):
  File "/usr/local/bin/seqenv", line 18, in <module>
    doc_params = re.findall('^### All parameters(.+?)###', readme_contents, flags=re.M|re.DOTALL)[0]
IndexError: list index out of range

I think this is an issue with the placement of the README.md file. Line 13 of /usr/local/bin/seqenv sets the README.md path as:

readme_path = current_dir + '../README.md'

This implies that the README.md file should be in /usr/local. In the case of my server, another README.md file was already there. I downloaded the seqenv README.md file from Github and copied it to /usr/local, and this seems to have resolved the issue. Seqenv now works.

Could this be avoided in the install, for example by placing the README.md file somewhere else, giving the README.md file a more unique name, or having a specific action to take when another README.md file is already in /usr/local?

**Comment by xapple** [comment]
Thanks for reporting this edge case. It would only happen when you have, by chance, a README file in `/usr/local/`

Is fixed in version 1.3.0
You can do `pip install seqenv --upgrade`
