### ISSUE TITLE
Pre-September 2016 nt database

### ISSUE THREAD

**Issue by Danread** [xapple/seqenv#7]
Do you have a source for a pre-September 2016 version of the nt database that I can use for seqenv?

Thank you,

Dan.

**Comment by xapple** [comment]
Yes, NCBI decided to remove their numbering scheme using "GI" identifiers from the NT database near the end of 2016, breaking the seqenv pipeline. It is unfortunate that they would not even provide access to either legacy indexes or archived database. Basically they left scientists out cold.

I have procured and uploaded a version of the NT database dating from _2015.01.07_ to dropbox. It is available here:

https://www.dropbox.com/s/fxqwc4uwi046av3/ncbi_nt_01_07_2015.fasta.gz?dl=0

The file is in FASTA format, gzip compressed and weighs 21.66 GB
